name: Deployment Pipeline

on:
  push:
    branches:
      - "main"
      - "develop"

env:
  ENVIRONMENT_NAME: ${{ fromJSON('{"develop":"dev", "qa":"qa", "main":"prod"}')[github.head_ref || github.ref_name ] }}
  IMAGE_NAME: pablo_page

jobs:
  build-and-push: 
    runs-on: ubuntu-20.04

    steps:

      - 
        name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Lint Action
        uses: wearerequired/lint-action@v2.0.1

      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Push
        uses: docker/build-push-action@v3
        with:
          file: dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:latest, 
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ env.ENVIRONMENT_NAME }}_${{ github.run_number }}
          contex: .